version: '3'

services:
  fanorona-telo:
    build: .
    image: fanorona-telo:latest
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./stats:/app/stats
      - ./assets:/app/assets
    network_mode: "host"
